### ISSUE TITLE
Create custom metadata for Outlook events

### ISSUE THREAD

**Issue by urmade** [microsoft-campus-community/MCC-App_Event-Engine#1]
# Description
Outlook events in office lacks some metadata to build an event page dynamically. This can be added via Schema extensions in Microsoft Graph.

# ToDos
Define and add new Schema to Outlook. Proposed metadata:
- status (In which phase of planning is the project)
- titleImageUrl (for display on website)
- requirePhotoAgreement (boolean to indicate if photos could be taken from the participant)
- supportRequestId (long-term field to handle event support requests automatically later on)

**Comment by MalteRei** [comment]
@Urmade I created the json for the schema extension. I can not POST it to the graph because I don't have the permissions for `Directory.AccessAsUser.All`
In addition I am not sure if Boolean is allowed as data type for targetTypes event. Why? In graph explorer I get an 400 error:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Property type is invalid for target types.",
        "innerError": {
            "request-id": "e9e3f30d-b95c-4988-ac64-fd9b7b41106f",
            "date": "2020-03-25T18:31:54"
        }
    }
}
```
When I change boolean to String it seems to work because then I get the error for missing permission.

**Comment by MalteRei** [comment]
Also could you explain to me the use case for the property requirePhotoAgreement ?

**Comment by urmade** [comment]
As stated in the reference events currently only support String arguments. So unfortunately all metadata has to be string based. 
Please post the current schema extension in this issue, I will update our database latest this weekend. Until then please start with using mock data.
As we want to spawn event websites from the object, we need a way to indicate if photos are taken on the event. Alternatively, we could just put this as a participation requirement on the website itself, basically saying that everyone agrees to get photographed when attending one of our events.

**Comment by MalteRei** [comment]
Schema extension:
```
{
    "id":"campus-community_mccevents",
    "description": "An schema extension for Outlook events to dynamically build an event page",
    "owner": "afb5a4f1-86df-4a57-9415-2a6bff08f04e",
    "targetTypes": [
        "Event"
    ],
    "properties": [
        {
            "name": "planningStatus",
            "type": "String"
        },
        {
            "name": "titleImageUrl",
            "type": "String"
        },
        {
            "name": "supportRequestId",
            "type": "String"
        },
        {
            "name": "requirePhotoAgreement",
            "type": "String"
        }
    ]
}
```

**Comment by MalteRei** [comment]
I understand the use case. Makes sense.

**Comment by MalteRei** [comment]
Sorry for asking so many questions. However, it helps me understanding the bigger picture and Microsoft Graph.
Why do you have to update the database?
Is the data not directly stored in Microsoft Graph?

**Comment by urmade** [comment]
Microsoft Graph stores an event with all the attributes that are necessary to use the objects in Office 365 (you can find a detailed list of attributes [here](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0#properties).

As this object lacks a few properties that we need to spawn an event for our own causes, we use a new [Schema extension](https://docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0).
This also reduces the risk of conflicting with Office 365 functionality as we don't use any properties in a way that wasn't intended by Microsoft.

**Comment by urmade** [comment]
@MalteRei: The schema extension is now available with the ID 'extvmri0qlh_eventEngine'. As '-' was not in the list of allowed characters, 'campus-community' didn't work. But you can still start working with this schema, despite the ugly ID.

**Comment by MalteRei** [comment]
Add friendly id to use in frontend to schema extension. This id has to be human readable and unique to identify an event.

**Comment by urmade** [comment]
Updated schema:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#schemaExtensions/$entity",
    "id": "extvmri0qlh_eventEngine",
    "description": "A schema extension for outlook events supporting the MCC event engine, e.g. to dynamically build an event page",
    "targetTypes": [
        "Event"
    ],
    "status": "Available",
    "properties": [
        {
            "name": "readableId",
            "type": "String"
        },
        {
            "name": "planningStatus",
            "type": "String"
        },
        {
            "name": "titleImageUrl",
            "type": "String"
        },
        {
            "name": "supportRequestId",
            "type": "String"
        },
        {
            "name": "requirePhotoAgreement",
            "type": "String"
        }
    ]
}
```

**Comment by MalteRei** [comment]
@urmade why is requirePhotoAgreement a string in your definition and not a boolean as you stated at the top of this issue:

> # Description
> Outlook events in office lacks some metadata to build an event page dynamically. This can be added via Schema extensions in Microsoft Graph.
> 
> # ToDos
> Define and add new Schema to Outlook. Proposed metadata:
> 
> * status (In which phase of planning is the project)
> * titleImageUrl (for display on website)
> * requirePhotoAgreement (boolean to indicate if photos could be taken from the participant)
> * supportRequestId (long-term field to handle event support requests automatically later on)

**Comment by urmade** [comment]
@MalteRei event items in MS Graph only allow string attributes in extensions. So we have to store it as a string and parse it back to boolean in the engine.

**Comment by MalteRei** [comment]
Alright
