### ISSUE TITLE
Change teams group events to an office group

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/MCC-App_Event-Engine#11]
## :mag_right: Short desciption
Under the events group the global calendar for events is supposed to be.

**Is your feature request related to a problem? Please describe.**
Currently the problem is that the events group is a MS Teams group and not an office group which is why it can not be used through the graph and needs to be migrated.

**Describe alternatives you've considered**
@Urmade and I have talked about the alternative of using one calendar for each campus. However, we come to the conclusion that every scenario can be covered with a global calendar. The organizers of an event will be stored as participants and the actual participants will have their emails and event id stored in a separate database. This way the database of participants can be cleared easily all 90 days to be GDPR compliant. Through the organizers of an event we can query which campuses are responsible for the event.

**Comment by urmade** [comment]
Done, Calendar ID: 7a77d007-2cd2-4cb5-bb71-5ff85aa92e82
